```{r include = FALSE}

library(dplyr)
library(ggplot2)
source("./R/constants.R")
```

Build the path to the 'all weather' single dataframe
```{r include = FALSE}
all_weather_single_dataframe_path <- paste0(
  DIR_TECHNICALLY_CORRECT_ALL,
  "/",
  WEATHER_ALL_DATA_FRAMES_NO_NAS
)
```
```{r}
all_weather_single_dataframe_path
```

Load the 'all weather' single dataframe
```{r include = FALSE}
all_weather_single_dataframe <- readRDS(
  all_weather_single_dataframe_path
)
```
```{r}
colnames(all_weather_single_dataframe)
```
Max temp_max_degrees_c
```{r}
max(all_weather_single_dataframe$temp_max_degrees_c, na.rm = TRUE)
```

Min temp_max_degrees_c
```{r}
min(all_weather_single_dataframe$temp_max_degrees_c, na.rm = TRUE)
```

Max temp_min_degrees_c
```{r}
max(all_weather_single_dataframe$temp_min_degrees_c, na.rm = TRUE)
```

Min temp_min_degrees_c
```{r}
min(all_weather_single_dataframe$temp_min_degrees_c, na.rm = TRUE)
```

Create dataframe to plot the above
```{r}
max_max <- max(all_weather_single_dataframe$temp_max_degrees_c, na.rm = TRUE)
max_min <- min(all_weather_single_dataframe$temp_max_degrees_c, na.rm = TRUE)
max_diff <- max_max - max_min

min_max <- max(all_weather_single_dataframe$temp_min_degrees_c, na.rm = TRUE)
min_min <- min(all_weather_single_dataframe$temp_min_degrees_c, na.rm = TRUE)
min_diff <- min_max - min_min

min_max_temps <- data.frame(
  `max` = as.double(
    c(
        max_max,
        max_min,
        max_diff
    )
  ),
  `min` = as.double(
    c(
        min_max,
        min_min,
        min_diff
    )
  ),
  `diff` = as.double(
    c(
        max_max - min_max,
        max_min - min_min,
        max_diff - min_diff
    )
  )
)

min_max_temps
```

```{r}

means <- all_weather_single_dataframe %>%
    group_by(weather_station_name) %>%
    dplyr::summarize(
      mean = mean(temp_max_degrees_c, na.rm=TRUE),
      sd = sd(temp_max_degrees_c, na.rm=TRUE)
    )

means
```

```{r}
hist(means$mean)
```

```{r}
hist(means$sd)
```

```{r}
means_by_month <- all_weather_single_dataframe %>%
    group_by(observation_month) %>%
    dplyr::summarize(
      mean = mean(temp_max_degrees_c, na.rm=TRUE),
      sd = sd(temp_max_degrees_c, na.rm=TRUE)
    )

means_by_month
```

```{r}
plot(y = means_by_month$mean, x = means_by_month$observation_month)
```

```{r}
ggplot(
  all_weather_single_dataframe,
  aes(
    x = observation_month,
    y = temp_max_degrees_c,
    fill = weather_station_name
  )
) + geom_boxplot() + 
  facet_wrap(~weather_station_name)
```

```{r}
nairn <- all_weather_single_dataframe %>% filter(weather_station_name == "nairn")

ggplot(
  nairn,
  aes(
    x = as.factor(observation_month),
    y = temp_max_degrees_c,
  )
) + geom_boxplot()
```

```{r}
nairn <- all_weather_single_dataframe %>% filter(weather_station_name == "nairn")

ggplot(
  nairn,
  aes(
    x = as.factor(observation_month),
    y = temp_min_degrees_c,
  )
) + geom_boxplot()
```

```{r}
nairn <- all_weather_single_dataframe %>% filter(weather_station_name == "nairn")

ggplot(
  nairn,
  aes(
    x = as.factor(observation_month),
    y = average_temp_degrees_c,
  )
) + geom_boxplot()
```

```{r}
heathrow <- all_weather_single_dataframe %>% filter(weather_station_name == "heathrow")

ggplot(
  nairn,
  aes(
    x = as.factor(observation_month),
    y = temp_max_degrees_c,
  )
) + geom_boxplot()
```

```{r}
heathrow <- all_weather_single_dataframe %>% filter(weather_station_name == "heathrow")

ggplot(
  nairn,
  aes(
    x = as.factor(observation_month),
    y = temp_min_degrees_c,
  )
) + geom_boxplot()
```

```{r}
heathrow <- all_weather_single_dataframe %>% filter(weather_station_name == "heathrow")

ggplot(
  nairn,
  aes(
    x = as.factor(observation_month),
    y = average_temp_degrees_c,
  )
) + geom_boxplot()
```