WELLBEING_DEST_FILE_NAME <- "2019-spring"
WELLBEING_SOURCE_FILE_NAME <- "spring2019"
WELLBEING_HAPPINESS_FILE_NAME <- "happiness"
DATA_RAW_WELLBEING_HAPPINESS_PATH <- paste0(
  DIR_RAW_DATA_WELLBEING,
  WELLBEING_HAPPINESS_FILE_NAME,
  FILE_EXTENSION_CSV
)
DATA_WELLBEING_HAPPINESS_PATH <- paste(
  DIR_DATA_WELLBEING,
  WELLBEING_HAPPINESS_FILE_NAME,
  FILE_EXTENSION_RDS
)
